#ifndef PAGER_H
#define PAGER_H

#define X86_PAGER_BITMASK_PRESENT 1 << 0
#define X86_PAGER_BITMASK_WRITABLE 1 << 1
#define X86_PAGER_BITMASK_USER 1 << 2
#define X86_PAGER_BITMASK_ADDR 0x000FFFFFFFFFF000
#define X86_PAGER_BITMASK_XD 1 << 63

#define PML4_GET_ADDR(VALUE) ((VALUE) & X86_PAGER_BITMASK_ADDR)
#define PML4_GET_FLAGS(VALUE) ((VALUE) & ~X86_PAGER_BITMASK_ADDR)

#endif